### ISSUE TITLE
Geometry Interfaces Module Level 1 Checklist

### ISSUE THREAD

**Issue by viell-dev** [viell-dev/fp-ts-dom#4]
# [Geometry Interfaces Module Level 1](https://www.w3.org/TR/2018/CR-geometry-1-20181204/)
_W3C Candidate Recommendation, 4 December 2018_

The `geometry-1` "tag" of the standard doesn't translate into JS names since `-` isn't a valid character in names. So `Geometry1` as a prefix instead? or `Geometry_1`? `G1`? I've used `Dom` for `dom`, `Html` for `html` and `Svg2` for `svg2`.

Currently using `Geometry1`, might change this later. Haven't decided yet.

## Dictionaries
- [x] [DOMPointInit](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#dictdef-dompointinit)
- [x] [DOMRectInit](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#dictdef-domrectinit)
- [x] [DOMQuadInit](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#dictdef-domquadinit)
- [x] [DOMMatrix2DInit](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#dictdef-dommatrix2dinit)
- [x] [DOMMatrixInit](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#dictdef-dommatrixinit)

## Interfaces
- [x] [DOMPointReadOnly](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#dompointreadonly)
- [x] [DOMPoint](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#dompoint)
- [x] [DOMRectReadOnly](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#domrectreadonly)
- [x] [DOMRect](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#domrect)
- [x] ~~[DOMRectList](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#domrectlist)~~ (skipped in favour of `DOMRect[]`)
  - Might want to skip this in favour of `DOMRect[]`. (#1)
- [x] [DOMQuad](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#domquad)
- [x] [DOMMatrixReadOnly](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#dommatrixreadonly)
- [x] [DOMMatrix](https://www.w3.org/TR/2018/CR-geometry-1-20181204/#dommatrix)

## Implementations
- [x] DOMPointReadOnly
- [x] DOMPoint
- [x] DOMRectReadOnly
- [x] DOMRect
- [x] ~~DOMRectList~~ (skipped in favour of `DOMRect[]`)
- [x] DOMQuad
- [x] DOMMatrixReadOnly
- [x] DOMMatrix

**Comment by viell-dev** [comment]
Relevant commits:
1. d78e0954490d4f6b854a2a094151fea09db02f57 DOMPoint dictionary and interfaces finalized
2. 6e9e1f0be3c16dc57b9865c634f5a78cafec9472 Spelling fix
3. 8e2ffabfc6972cbf84b7c804710d201ffa574145 Fixed typing of matrixTransform
4. 883a2d8aa14e7450d065e76e1e3d056436c98edd DOMRect dictionary and interfaces finalized
5. ba3c18846bac5f35f54af0d722494ae2509e0859 DOMQuad dictionary and interfaces finalized
6. 5e4de2a5d51a4cede0416437686d90760653662c Removed DOMRectList interface
7. f0afeffe96da5d911ee95dff0452627a2e6d21a7 DOMMatrix dictionaries and interfaces finalized
