### ISSUE TITLE
Scalable Vector Graphics (SVG) 2 Checklist

### ISSUE THREAD

**Issue by viell-dev** [viell-dev/fp-ts-dom#6]
# [Scalable Vector Graphics (SVG) 2](https://www.w3.org/TR/2018/CR-SVG2-20181004/)
*W3C Candidate Recommendation 04 October 2018*

## Constants
- [ ] [SVGLength](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGLength) - Length Unit Types
- [ ] [SVGAngle](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAngle) - Angle Unit Types
- [ ] [SVGUnitTypes](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGUnitTypes) - Unit Types
- [ ] [SVGZoomAndPan](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGZoomAndPan) - Zoom and Pan Types
- [ ] [SVGTransform](https://www.w3.org/TR/2018/CR-SVG2-20181004/coords.html#InterfaceSVGTransform) - Transform Types
- [ ] [SVGPreserveAspectRatio](https://www.w3.org/TR/2018/CR-SVG2-20181004/coords.html#InterfaceSVGPreserveAspectRatio) - Alignment Types
- [ ] [SVGPreserveAspectRatio](https://www.w3.org/TR/2018/CR-SVG2-20181004/coords.html#InterfaceSVGPreserveAspectRatio) - Meet-or-slice Types
- [ ] [SVGTextContentElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/text.html#InterfaceSVGTextContentElement) - lengthAdjust Types
- [ ] [SVGTextPathElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/text.html#InterfaceSVGTextPathElement) - textPath Method Types
- [ ] [SVGTextPathElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/text.html#InterfaceSVGTextPathElement) - textPath Spacing Types
- [ ] [SVGMarkerElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/painting.html#InterfaceSVGMarkerElement) - Marker Unit Types
- [ ] [SVGMarkerElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/painting.html#InterfaceSVGMarkerElement) - Marker Orientation Types
- [ ] [SVGGradientElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/pservers.html#InterfaceSVGGradientElement) - Spread Method Types

## Dictionaries
- [ ] [SVGBoundingBoxOptions](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#SVGBoundingBoxOptions)

## Interfaces
- [ ] [SVGElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGElement)
- [ ] [SVGGraphicsElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGGraphicsElement)
- [ ] [SVGGeometryElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGGeometryElement)
- [ ] [SVGNumber](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGNumber)
- [ ] [SVGLength](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGLength)
- [ ] [SVGAngle](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAngle)
- [ ] [SVGNumberList](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGNumberList)
- [ ] [SVGLengthList](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGLengthList)
- [ ] [SVGStringList](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGStringList)
- [ ] [SVGAnimatedBoolean](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAnimatedBoolean)
- [ ] [SVGAnimatedEnumeration](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAnimatedEnumeration)
- [ ] [SVGAnimatedInteger](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAnimatedInteger)
- [ ] [SVGAnimatedNumber](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAnimatedNumber)
- [ ] [SVGAnimatedLength](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAnimatedLength)
- [ ] [SVGAnimatedAngle](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAnimatedAngle)
- [ ] [SVGAnimatedString](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAnimatedString)
- [ ] [SVGAnimatedRect](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAnimatedRect)
- [ ] [SVGAnimatedNumberList](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAnimatedNumberList)
- [ ] [SVGAnimatedLengthList](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGAnimatedLengthList)
- [ ] [SVGUnitTypes](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGUnitTypes)
- [ ] [Document](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceDocumentExtensions)
- [ ] [SVGSVGElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGSVGElement)
- [ ] [SVGGElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGGElement)
- [ ] [SVGUnknownElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGUnknownElement)
- [ ] [SVGDefsElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGDefsElement)
- [ ] [SVGDescElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGDescElement)
- [ ] [SVGMetadataElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGMetadataElement)
- [ ] [SVGTitleElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGTitleElement)
- [ ] [SVGSymbolElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGSymbolElement)
- [ ] [SVGUseElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGUseElement)
- [ ] [SVGUseElementShadowRoot](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGUseElementShadowRoot)
- [ ] [ShadowAnimation](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceShadowAnimation)
- [ ] [SVGSwitchElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGSwitchElement)
- [ ] [SVGStyleElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/styling.html#InterfaceSVGStyleElement)
- [ ] [SVGTransform](https://www.w3.org/TR/2018/CR-SVG2-20181004/coords.html#InterfaceSVGTransform)
- [ ] [SVGTransformList](https://www.w3.org/TR/2018/CR-SVG2-20181004/coords.html#InterfaceSVGTransformList)
- [ ] [SVGAnimatedTransformList](https://www.w3.org/TR/2018/CR-SVG2-20181004/coords.html#InterfaceSVGAnimatedTransformList)
- [ ] [SVGPreserveAspectRatio](https://www.w3.org/TR/2018/CR-SVG2-20181004/coords.html#InterfaceSVGPreserveAspectRatio)
- [ ] [SVGAnimatedPreserveAspectRatio](https://www.w3.org/TR/2018/CR-SVG2-20181004/coords.html#InterfaceSVGAnimatedPreserveAspectRatio)
- [ ] [SVGPathElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/paths.html#InterfaceSVGPathElement)
- [ ] [SVGRectElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/shapes.html#InterfaceSVGRectElement)
- [ ] [SVGCircleElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/shapes.html#InterfaceSVGCircleElement)
- [ ] [SVGEllipseElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/shapes.html#InterfaceSVGEllipseElement)
- [ ] [SVGLineElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/shapes.html#InterfaceSVGLineElement)
- [ ] [SVGPointList](https://www.w3.org/TR/2018/CR-SVG2-20181004/shapes.html#InterfaceSVGPointList)
- [ ] [SVGPolylineElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/shapes.html#InterfaceSVGPolylineElement)
- [ ] [SVGPolygonElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/shapes.html#InterfaceSVGPolygonElement)
- [ ] [SVGTextContentElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/text.html#InterfaceSVGTextContentElement)
- [ ] [SVGTextPositioningElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/text.html#InterfaceSVGTextPositioningElement)
- [ ] [SVGTextElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/text.html#InterfaceSVGTextElement)
- [ ] [SVGTSpanElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/text.html#InterfaceSVGTSpanElement)
- [ ] [SVGTextPathElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/text.html#InterfaceSVGTextPathElement)
- [ ] [SVGImageElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/embedded.html#InterfaceSVGImageElement)
- [ ] [SVGForeignObjectElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/embedded.html#InterfaceSVGForeignObjectElement)
- [ ] [SVGMarkerElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/painting.html#InterfaceSVGMarkerElement)
- [ ] [SVGGradientElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/pservers.html#InterfaceSVGGradientElement)
- [ ] [SVGLinearGradientElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/pservers.html#InterfaceSVGLinearGradientElement)
- [ ] [SVGRadialGradientElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/pservers.html#InterfaceSVGRadialGradientElement)
- [ ] [SVGStopElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/pservers.html#InterfaceSVGStopElement)
- [ ] [SVGPatternElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/pservers.html#InterfaceSVGPatternElement)
- [ ] [SVGScriptElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/interact.html#InterfaceSVGScriptElement)
- [ ] [SVGAElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/linking.html#InterfaceSVGAElement)
- [ ] [SVGViewElement](https://www.w3.org/TR/2018/CR-SVG2-20181004/linking.html#InterfaceSVGViewElement)

## Mixins
- [ ] [SVGTests](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGTests)
- [ ] [SVGFitToViewBox](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGFitToViewBox)
- [ ] [SVGZoomAndPan](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGZoomAndPan)
- [ ] [SVGURIReference](https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGURIReference)
- [ ] [SVGElementInstance](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceSVGElementInstance)
- [ ] [GetSVGDocument](https://www.w3.org/TR/2018/CR-SVG2-20181004/struct.html#InterfaceGetSVGDocument)
- [ ] [SVGAnimatedPoints](https://www.w3.org/TR/2018/CR-SVG2-20181004/shapes.html#InterfaceSVGAnimatedPoints)
