### ISSUE TITLE
HTML Checklist

### ISSUE THREAD

**Issue by viell-dev** [viell-dev/fp-ts-dom#7]
# [HTML](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/)
*Commit Snapshot — Last Updated 30 August 2022*

** TODO: Finish the checklist! **

## Callbacks
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()

## Dictionaries
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()

## Enums
- [ ] [DocumentReadyState](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-document-object)
- [ ] [DocumentVisibilityState](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-document-object)
- [ ] [CanPlayTypeResult](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#media-elements)
- [ ] [TextTrackMode](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#text-track-api)
- [ ] [TextTrackKind](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#text-track-api)
- [ ] []()
- [ ] []()
- [ ] []()

## Interfaces
- [ ] [HTMLAllCollection](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-htmlallcollection-interface)
- [ ] [HTMLFormControlsCollection](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-htmlformcontrolscollection-interface)
- [ ] [RadioNodeList](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-htmlformcontrolscollection-interface)
- [ ] [HTMLOptionsCollection](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-htmloptionscollection-interface)
- [ ] [DOMStringList](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-domstringlist-interface)
- [ ] [Document](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-document-object)
- [ ] [HTMLElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#elements-in-the-dom)
- [ ] [DOMStringMap](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#embedding-custom-non-visible-data-with-the-data-*-attributes)
- [ ] [HTMLHtmlElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-html-element)
- [ ] [HTMLHeadElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-head-element)
- [ ] [HTMLTitleElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-title-element)
- [ ] [HTMLBaseElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-base-element)
- [ ] [HTMLLinkElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-link-element)
- [ ] [HTMLMetaElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-meta-element)
- [ ] [HTMLStyleElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-style-element)
- [ ] [HTMLBodyElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-body-element)
- [ ] [HTMLHeadingElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements)
- [ ] [HTMLParagraphElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-p-element)
- [ ] [HTMLHRElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-hr-element)
- [ ] [HTMLPreElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-pre-element)
- [ ] [HTMLQuoteElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-blockquote-element)
- [ ] [HTMLOListElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-ol-element)
- [ ] [HTMLUListElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-ul-element)
- [ ] [HTMLMenuElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-menu-element)
- [ ] [HTMLLIElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-li-element)
- [ ] [HTMLDListElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-dl-element)
- [ ] [HTMLDivElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-div-element)
- [ ] [HTMLAnchorElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-a-element)
- [ ] [HTMLDataElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-data-element)
- [ ] [HTMLTimeElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-time-element)
- [ ] [HTMLSpanElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-span-element)
- [ ] [HTMLBRElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-br-element)
- [ ] [HTMLModElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#attributes-common-to-ins-and-del-elements)
- [ ] [HTMLPictureElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-picture-element)
- [ ] [HTMLSourceElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-source-element)
- [ ] [HTMLImageElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-img-element)
- [ ] [HTMLIFrameElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-iframe-element)
- [ ] [HTMLEmbedElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-embed-element)
- [ ] [HTMLObjectElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-object-element)
- [ ] [HTMLVideoElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-video-element)
- [ ] [HTMLAudioElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-audio-element)
- [ ] [HTMLTrackElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-track-element)
- [ ] [HTMLMediaElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#media-elements)
- [ ] [MediaError](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#error-codes)
- [ ] [AudioTrackList](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#audiotracklist-and-videotracklist-objects)
- [ ] [AudioTrack](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#audiotracklist-and-videotracklist-objects)
- [ ] [VideoTrackList](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#audiotracklist-and-videotracklist-objects)
- [ ] [VideoTrack](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#audiotracklist-and-videotracklist-objects)
- [ ] [TextTrackList](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#text-track-api)
- [ ] [TextTrack](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#text-track-api)
- [ ] [TextTrackCueList](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#text-track-api)
- [ ] [TextTrackCue](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#text-track-api)
- [ ] [TimeRanges](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#time-ranges)
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()

## Mixins
- [ ] [DocumentOrShadowRoot](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-documentorshadowroot-interface)
- [ ] [HTMLOrSVGElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#elements-in-the-dom)
- [ ] [HTMLHyperlinkElementUtils](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#api-for-a-and-area-elements)
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()

## Typedefs
- [ ] [HTMLOrSVGScriptElement](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#the-document-object)
- [ ] [MediaProvider](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#media-elements)
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()

**Comment by viell-dev** [comment]
> The [HTMLAllCollection](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#htmlallcollection) interface is used for the legacy [document.all](https://html.spec.whatwg.org/commit-snapshots/c7ad0990516bae9d1bc3009145a8bcde523b584d/#dom-document-all) attribute.
As such I will also be skipping `document.all`.
