### ISSUE TITLE
DOM Checklist

### ISSUE THREAD

**Issue by viell-dev** [viell-dev/fp-ts-dom#8]
# [DOM](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/)
*Commit Snapshot — Last Updated 25 August 2022*

## Callbacks
- [x] [EventListener](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#callbackdef-eventlistener)
- [x] [MutationCallback](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#callbackdef-mutationcallback)
- [x] [NodeFilter](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#callbackdef-nodefilter)
- [x] ~~[XPathNSResolver](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#callbackdef-xpathnsresolver)~~
  - Skipped for now, since API definition is incomplete.

## Constants
- [x] [Event EventPhase](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#event)
- [x] [Node NodeType](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#node)
- [x] [Node DocumentPosition](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#node)
- [x] [NodeFilter WhatToShow](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#callbackdef-nodefilter)
- [x] [NodeFilter Filter](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#callbackdef-nodefilter)
- [x] [Range How](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#range)
- [x] ~~[XPathResult ResultTypes](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#xpathresult)~~
  - Skipped for now, since API definition is incomplete.

## Dictionaries
- [x] [EventInit](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dictdef-eventinit)
- [x] [CustomEventInit](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dictdef-customeventinit)
- [x] [EventListenerOptions](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dictdef-eventlisteneroptions)
- [x] [AddEventListenerOptions](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dictdef-addeventlisteneroptions)
- [x] [MutationObserverInit](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dictdef-mutationobserverinit)
- [x] [GetRootNodeOptions](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dictdef-getrootnodeoptions)
- [x] [ElementCreationOptions](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dictdef-elementcreationoptions)
- [x] [ShadowRootInit](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dictdef-shadowrootinit)
- [x] [StaticRangeInit](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dictdef-staticrangeinit)

## Enums
- [x] [ShadowRootMode](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#enumdef-shadowrootmode)
- [x] [SlotAssignmentMode](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#enumdef-slotassignmentmode)

## Interfaces
- [x] [Event](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#event)
- [x] ~~[Window (partial)](https://html.spec.whatwg.org/multipage/window-object.html#window)~~
  - Legacy extension skipped.
    >**Note:** Web developers are strongly encouraged to instead rely on the [Event](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#event) object passed to event listeners, as that will result in more portable code. This attribute is not available in workers or worklets, and is inaccurate for events dispatched in [shadow trees](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#concept-shadow-tree).
- [x] [CustomEvent](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#customevent)
- [x] [EventTarget](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#eventtarget)
- [x] [AbortController](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#abortcontroller)
- [x] [AbortSignal](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#abortsignal)
- [x] ~~[NodeList](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#nodelist)~~
  - Old-style collection skipped.
- [x] ~~[HTMLCollection](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#htmlcollection)~~
  -  Old-style collection and historical artefact skipped.
    > **Note:** [HTMLCollection](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#htmlcollection) is a historical artifact we cannot rid the web of. While developers are of course welcome to keep using it, new API standard designers ought not to use it (use sequence<T> in IDL instead).
- [x] [MutationObserver](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#mutationobserver)
- [x] [MutationRecord](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#mutationrecord)
- [x] [Node](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#node)
- [x] [Document](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#document)
- [x] [XMLDocument](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#xmldocument)
- [x] [DOMImplementation](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#domimplementation)
- [x] [DocumentType](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#documenttype)
- [x] [DocumentFragment](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#documentfragment)
- [x] [ShadowRoot](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#shadowroot)
- [x] [Element](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#element)
- [x] [NamedNodeMap](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#namednodemap)
- [x] [Attr](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#attr)
- [x] [CharacterData](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#characterdata)
- [x] [Text](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#text)
- [x] [CDATASection](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#cdatasection)
- [x] [ProcessingInstruction](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#processinginstruction)
- [x] [Comment](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#comment)
- [x] [AbstractRange](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#abstractrange)
- [x] [StaticRange](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#staticrange)
- [x] [Range](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#range)
- [x] [NodeIterator](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#nodeiterator)
- [x] [TreeWalker](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#treewalker)
- [x] [DOMTokenList](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#domtokenlist)
- [x] ~~[XPathResult](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#xpathresult)~~
  - Skipped for now, since API definition is incomplete.
- [x] ~~[XPathExpression](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#xpathexpression)~~
  - Skipped for now, since API definition is incomplete.
- [x] ~~[XPathEvaluator](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#xpathevaluator)~~
  - Skipped for now, since API definition is incomplete.
- [x] ~~[XSLTProcessor](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#xsltprocessor)~~
  - Skipped for now, since API definition is incomplete.

## Mixins
- [x] [NonElementParentNode](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#nonelementparentnode)
- [x] [DocumentOrShadowRoot](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#documentorshadowroot)
- [x] [ParentNode](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#parentnode)
- [x] [NonDocumentTypeChildNode](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#nondocumenttypechildnode)
- [x] [ChildNode](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#childnode)
- [x] [Slottable](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#slotable)
- [x] ~~[XPathEvaluatorBase](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#xpathevaluatorbase)~~
  - Skipped for now, since API definition is incomplete.

## Implementations
- [x] Event
- [x] CustomEvent
- [x] EventTarget
- [x] AbortController
- [x] AbortSignal
- [x] MutationObserver
- [x] MutationRecord
- [x] Node
- [x] Document
- [x] XMLDocument
- [x] DOMImplementation
- [x] DocumentType
- [x] DocumentFragment
- [x] ShadowRoot
- [x] Element
- [x] NamedNodeMap
- [x] Attr
- [x] CharacterData
- [x] Text
- [x] CDATASection
- [x] ProcessingInstruction
- [x] Comment
- [x] AbstractRange
- [x] StaticRange
- [x] Range
- [x] NodeIterator
- [x] TreeWalker
- [x] DOMTokenList

**Comment by viell-dev** [comment]
It is noted in [2.1. Introduction to "DOM Events"](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#introduction-to-dom-events) that an event listeners callback is:
> typically a JavaScript Function

And it's not mentioned again in [2.7. Interface EventTarget](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#interface-eventtarget). Where it is instead only stated that the callback should be an object with a `handleEvent()` method. (aka. EventListener)
> **callback** null or an `EventListener` object

```webidl
callback interface EventListener {
  undefined handleEvent(Event event);
};
```

Seems like a slight oversight in my opinion. At least MDN made it clear that it can be a function. And that's how I've used it; since forever... So it was a little confusing to me when the callback had to be an object according to the spec.

---

We will use a function or object union types for callbacks that support either.

Notably the `MutationCallback` appears to be the only on that cannot be an object.

**Comment by viell-dev** [comment]
I'm skipping the [`hasFeature()`](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dom-domimplementation-hasfeature) method on `DOMImplementation` since it always returns `true`.

It's essentially deprecated and only kept for backwards-compatibility. Which isn't a concern for this package.

Note from the spec:
>`hasFeature()` originally would report whether the user agent claimed to support a given DOM feature, but experience proved it was not nearly as reliable or granular as simply checking whether the desired objects, attributes, or methods existed. As such, it is no longer to be used, but continues to exist (and simply returns true) so that old pages don’t stop working.

**Comment by viell-dev** [comment]
Skipping [`specified`](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dom-attr-specified) in `Attr` since:
> useless; always returns true

**Comment by viell-dev** [comment]
The methods on [`CharacterData`](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#characterdata) can throw `"IndexSizeError" DOMException`.

I've replaced these with `RangeError`. The plan is to return a `RangeError` with the same message as the deprecated `"IndexSizeError" DOMException` and include it as the `cause`.

Will probably do the same/similar things for other deprecated `DOMException` throws. If there are any...

**Comment by viell-dev** [comment]
Skipping [`detach()`](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#dom-range-detach) in `Range` since:
> Its functionality (disabling a `Range` object) was removed, but the method itself is preserved for compatibility.

**Comment by viell-dev** [comment]
### XPath

Skipping, for now, since API definition is incomplete.
> DOM Level 3 XPath defined an API for evaluating XPath 1.0 expressions. These APIs are widely implemented, but have not been maintained. The interface definitions are maintained here so that they can be updated when Web IDL changes. Complete definitions of these APIs remain necessary and such work is tracked and can be contributed to in [whatwg/dom#67](https://github.com/whatwg/dom/issues/67). [[DOM-Level-3-XPath]](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#biblio-dom-level-3-xpath) [[XPath]](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#biblio-xpath) [[WEBIDL]](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#biblio-webidl)

### XSLT
Skipping, for now, since API definition is incomplete.
> XSL Transformations (XSLT) is a language for transforming XML documents into other XML documents. The APIs defined in this section have been widely implemented, and are maintained here so that they can be updated when Web IDL changes. Complete definitions of these APIs remain necessary and such work is tracked and can be contributed to in [whatwg/dom#181](https://github.com/whatwg/dom/issues/181). [[XSLT]](https://dom.spec.whatwg.org/commit-snapshots/fa3aea5ff68161cabe9a3fe95fe6240a4ddd4412/#biblio-xslt)
