### ISSUE TITLE
High Resolution Time Checklist

### ISSUE THREAD

**Issue by viell-dev** [viell-dev/fp-ts-dom#9]
# [High Resolution Time](https://www.w3.org/TR/2022/WD-hr-time-3-20220128/)
*W3C Working Draft 28 January 2022*

## Interfaces
- [ ] [Performance](https://www.w3.org/TR/2022/WD-hr-time-3-20220128/#dom-performance)

## Mixins
- [ ] [WindowOrWorkerGlobalScope (partial)](https://www.w3.org/TR/2022/WD-hr-time-3-20220128/#extensions-to-windoworworkerglobalscope-mixin)

## Typedefs
- [ ] [DOMHighResTimeStamp](https://www.w3.org/TR/2022/WD-hr-time-3-20220128/#dom-domhighrestimestamp)
- [ ] [EpochTimeStamp](https://www.w3.org/TR/2022/WD-hr-time-3-20220128/#dom-epochtimestamp)
